services: docker

jobs:
  include:
    - stage: lint & test
      name: "Linter"
      script: docker build -t app-feup . && docker run -it app-feup flutter analyze --no-pub --preamble .
    - script: docker build -t app-feup . && docker run -it app-feup flutter test
      name: "Unit test"
