services: docker
before_script: docker build -t app-feup .


jobs:
  include:
    - stage: lint & test
      name: "Linter"
      script: docker run -it app-feup flutter analyze --no-pub --preamble .
    - script: docker run -it app-feup flutter test
      name: "Unit test"
